# Welcome to Jekyll!
#

# Site settings
title: Justin <3 Steph
description: |
  Do the thing or don't
owner: Justin Johnson # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: jwj019@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justinlovessteph.com" # the base hostname & protocol for your site
social:
  github: https://github.com/JohnsonWedding
  facebook-official: https://facebook.com/diskoo
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
